defmodule HydraAgent.Simulations.PortableArchive do
  @moduledoc "Fail-closed, deterministic ZIP boundary for Hydra portable artifacts."

  import Bitwise

  alias HydraAgent.Simulations.ContentHash

  @max_archive_bytes 8_000_000
  @max_uncompressed_bytes 64_000_000
  @max_file_bytes 32_000_000
  @max_entries 64
  @fixed_zip_time {{2020, 1, 1}, {0, 0, 0}}
  @roots %{simpack: "hydra-simpack/", run: "hydra-run/"}
  @formats %{simpack: "hydra-simpack", run: "hydra-run"}
  @executable_extensions ~w(
    .beam .ex .exs .eex .heex .js .mjs .cjs .ts .sh .bash .zsh .fish
    .py .rb .pl .php .jar .class .dll .so .dylib .exe .com .bat .cmd .ps1
    .app .apk
  )

  def limits do
    %{
      compressed_bytes: @max_archive_bytes,
      uncompressed_bytes: @max_uncompressed_bytes,
      per_file_bytes: @max_file_bytes,
      entries: @max_entries
    }
  end

  def create(kind, files, manifest, filename)
      when kind in [:simpack, :run] and is_map(files) and is_map(manifest) and
             is_binary(filename) do
    with :ok <- validate_output_files(files),
         manifest <- finalize_manifest(kind, files, manifest),
         files <- Map.put(files, "manifest.json", json(manifest)),
         {:ok, binary} <- create_zip(kind, files),
         :ok <- validate_compressed_size(binary) do
      {:ok,
       %{
         binary: binary,
         filename: filename,
         manifest: manifest,
         content_hash: manifest["content_hash"],
         byte_size: byte_size(binary)
       }}
    end
  end

  def create(_kind, _files, _manifest, _filename),
    do: error(:invalid_archive_input, "Portable artifact files and manifest are required")

  def import(kind, binary) when kind in [:simpack, :run] and is_binary(binary) do
    with :ok <- validate_compressed_size(binary),
         :ok <- validate_central_directory(binary),
         {:ok, table} <- zip_table(binary),
         :ok <- validate_entries(kind, table),
         {:ok, files} <- extract(kind, binary),
         :ok <- validate_extracted_files(files),
         {:ok, manifest} <- parse_manifest(files),
         :ok <- validate_manifest(kind, manifest, files) do
      {:ok,
       %{
         manifest: manifest,
         files: Map.delete(files, "manifest.json"),
         content_hash: manifest["content_hash"],
         byte_size: byte_size(binary)
       }}
    end
  end

  def import(_kind, _binary),
    do: error(:invalid_archive, "Portable artifact must be binary ZIP data")

  def json(value), do: Jason.encode!(value, pretty: true) <> "\n"

  defp finalize_manifest(kind, files, manifest) do
    hashes =
      files
      |> Enum.sort_by(&elem(&1, 0))
      |> Map.new(fn {path, content} -> {path, "sha256:" <> sha256(content)} end)

    semantic =
      manifest
      |> stringify_keys()
      |> Map.drop(["files", "content_hash"])
      |> Map.put("format", @formats[kind])
      |> Map.put("files", hashes)

    Map.put(semantic, "content_hash", ContentHash.digest(semantic))
  end

  defp validate_output_files(files) do
    cond do
      map_size(files) == 0 or map_size(files) + 1 > @max_entries ->
        error(:too_many_files, "Portable artifact contains an invalid number of files")

      Map.has_key?(files, "manifest.json") ->
        error(:reserved_path, "manifest.json is generated by Hydra")

      true ->
        Enum.reduce_while(files, {:ok, 0}, fn {path, content}, {:ok, total} ->
          with :ok <- validate_relative_path(path),
               true <- is_binary(content),
               true <- byte_size(content) <= @max_file_bytes,
               true <- total + byte_size(content) <= @max_uncompressed_bytes,
               :ok <- reject_executable(path, content) do
            {:cont, {:ok, total + byte_size(content)}}
          else
            {:error, _reason} = error -> {:halt, error}
            false -> {:halt, error(:file_too_large, "Portable artifact exceeds its size limit")}
          end
        end)
        |> case do
          {:ok, _total} -> :ok
          {:error, _reason} = error -> error
        end
    end
  end

  defp validate_compressed_size(binary) do
    if byte_size(binary) <= @max_archive_bytes,
      do: :ok,
      else: error(:archive_too_large, "Compressed portable artifact exceeds the 8 MB limit")
  end

  defp validate_central_directory(binary) do
    with {:ok, %{offset: offset, size: size, entries: entries}} <-
           end_of_central_directory(binary),
         true <- offset + size <= byte_size(binary),
         central <- binary_part(binary, offset, size),
         :ok <- validate_central_entries(central, entries) do
      :ok
    else
      {:error, _reason} = error -> error
      _ -> error(:invalid_archive, "Portable artifact has an invalid central directory")
    end
  end

  defp end_of_central_directory(binary) do
    :binary.matches(binary, <<0x06054B50::little-32>>)
    |> Enum.reverse()
    |> Enum.find_value(fn {position, _length} -> parse_eocd_at(binary, position) end)
    |> case do
      nil -> error(:invalid_archive, "Portable artifact has no end-of-directory record")
      record -> {:ok, record}
    end
  end

  defp parse_eocd_at(binary, position) do
    if byte_size(binary) - position >= 22 do
      <<_prefix::binary-size(position), 0x06054B50::little-32, disk::little-16,
        central_disk::little-16, disk_entries::little-16, entries::little-16,
        central_size::little-32, central_offset::little-32, comment_size::little-16,
        _rest::binary>> = binary

      if disk == 0 and central_disk == 0 and disk_entries == entries and
           position + 22 + comment_size == byte_size(binary) do
        %{offset: central_offset, size: central_size, entries: entries}
      end
    end
  end

  defp validate_central_entries(<<>>, 0), do: :ok

  defp validate_central_entries(
         <<0x02014B50::little-32, _made_by::little-16, _needed::little-16, flags::little-16,
           method::little-16, _time::little-16, _date::little-16, _crc::little-32,
           compressed_size::little-32, uncompressed_size::little-32, path_size::little-16,
           extra_size::little-16, comment_size::little-16, _disk::little-16, _internal::little-16,
           external::little-32, _offset::little-32, path::binary-size(path_size),
           _extra::binary-size(extra_size), _comment::binary-size(comment_size), rest::binary>>,
         entries
       )
       when entries > 0 do
    unix_mode = external >>> 16
    file_type = band(unix_mode, 0o170000)

    cond do
      band(flags, 0x1) != 0 ->
        error(:encrypted_archive, "Encrypted portable artifacts are not supported")

      method not in [0, 8] ->
        error(:unsupported_compression, "Portable artifact uses unsupported compression", method)

      compressed_size == 0xFFFFFFFF or uncompressed_size == 0xFFFFFFFF ->
        error(:unsupported_zip64, "ZIP64 portable artifacts are not supported")

      file_type not in [0, 0o040000, 0o100000] ->
        error(:unsafe_file_type, "Symlinks and special files are not allowed", %{
          path: path,
          mode: unix_mode
        })

      true ->
        validate_central_entries(rest, entries - 1)
    end
  end

  defp validate_central_entries(_central, _entries),
    do: error(:invalid_archive, "Portable artifact has malformed central-directory entries")

  defp zip_table(binary) do
    case :zip.table(binary) do
      {:ok, table} -> {:ok, table}
      {:error, reason} -> error(:invalid_archive, "Portable artifact is not a valid ZIP", reason)
    end
  rescue
    exception -> error(:invalid_archive, "Portable artifact could not be inspected", exception)
  catch
    kind, reason ->
      error(:invalid_archive, "Portable artifact could not be inspected", {kind, reason})
  end

  defp validate_entries(kind, table) do
    entries = Enum.reject(table, &match?({:zip_comment, _}, &1))

    if length(entries) > @max_entries do
      error(:too_many_files, "Portable artifact contains more than #{@max_entries} entries")
    else
      validate_entry_list(kind, entries, MapSet.new(), 0)
    end
  end

  defp validate_entry_list(_kind, [], _seen, total) when total <= @max_uncompressed_bytes,
    do: :ok

  defp validate_entry_list(_kind, [], _seen, _total),
    do: error(:archive_too_large, "Uncompressed portable artifact exceeds the 64 MB limit")

  defp validate_entry_list(
         kind,
         [{:zip_file, raw_name, file_info, _comment, _offset, compressed_size} | rest],
         seen,
         total
       ) do
    stat = File.Stat.from_record(file_info)

    with {:ok, path} <- normalize_archive_path(kind, raw_name),
         :ok <- validate_entry_type(path, stat),
         :ok <- validate_entry_sizes(stat.size, compressed_size),
         :ok <- reject_duplicate(path, seen),
         :ok <- reject_executable_path(path, stat.mode) do
      validate_entry_list(kind, rest, MapSet.put(seen, path), total + stat.size)
    end
  end

  defp validate_entry_list(_kind, [_unknown | _rest], _seen, _total),
    do: error(:invalid_archive, "Portable artifact contains an unsupported ZIP entry")

  defp normalize_archive_path(kind, raw_name) do
    root = @roots[kind]

    with {:ok, name} <- to_utf8(raw_name) do
      path = String.replace(name, "\\", "/")
      segments = String.split(path, "/", trim: false)

      cond do
        path == "" or String.contains?(path, <<0>>) ->
          error(:unsafe_path, "Portable artifact contains an empty or invalid path")

        String.starts_with?(path, "/") or Regex.match?(~r/^[A-Za-z]:\//, path) ->
          error(:unsafe_path, "Portable artifact contains an absolute path", path)

        ".." in segments or "." in segments ->
          error(:unsafe_path, "Portable artifact contains path traversal", path)

        not String.starts_with?(path, root) ->
          error(:unsafe_path, "Every portable artifact file must be inside #{root}", path)

        true ->
          {:ok, path}
      end
    end
  end

  defp validate_relative_path(path) when is_binary(path) do
    segments = String.split(String.replace(path, "\\", "/"), "/", trim: false)

    cond do
      path == "" or String.contains?(path, <<0>>) ->
        error(:unsafe_path, "Portable artifact contains an empty or invalid path")

      String.starts_with?(path, "/") or Regex.match?(~r/^[A-Za-z]:\//, path) ->
        error(:unsafe_path, "Portable artifact contains an absolute path", path)

      ".." in segments or "." in segments or "" in segments ->
        error(:unsafe_path, "Portable artifact contains an unsafe path", path)

      true ->
        :ok
    end
  end

  defp validate_relative_path(_path),
    do: error(:unsafe_path, "Portable artifact contains an invalid path")

  defp to_utf8(name) when is_list(name) do
    case :unicode.characters_to_binary(name) do
      binary when is_binary(binary) ->
        if String.valid?(binary),
          do: {:ok, binary},
          else: error(:invalid_filename, "Portable artifact contains a non-UTF-8 filename")

      _ ->
        error(:invalid_filename, "Portable artifact contains a non-UTF-8 filename")
    end
  rescue
    _ -> error(:invalid_filename, "Portable artifact contains a non-UTF-8 filename")
  end

  defp to_utf8(name) when is_binary(name) do
    if String.valid?(name),
      do: {:ok, name},
      else: error(:invalid_filename, "Portable artifact contains a non-UTF-8 filename")
  end

  defp to_utf8(_name), do: error(:invalid_filename, "Portable artifact filename is invalid")

  defp validate_entry_type(path, %File.Stat{type: type, mode: mode}) do
    cond do
      is_integer(mode) and band(mode, 0o170000) == 0o120000 ->
        error(:unsafe_file_type, "Symlinks and special files are not allowed", path)

      type == :directory and String.ends_with?(path, "/") ->
        :ok

      type == :regular ->
        :ok

      true ->
        error(:unsafe_file_type, "Symlinks and special files are not allowed", path)
    end
  end

  defp validate_entry_sizes(size, compressed_size)
       when is_integer(size) and size >= 0 and is_integer(compressed_size) and
              compressed_size >= 0 do
    if size <= @max_file_bytes,
      do: :ok,
      else: error(:file_too_large, "A portable artifact file exceeds the 32 MB limit")
  end

  defp validate_entry_sizes(_size, _compressed_size),
    do: error(:invalid_archive, "Portable artifact contains invalid file sizes")

  defp reject_duplicate(path, seen) do
    if MapSet.member?(seen, path),
      do: error(:duplicate_path, "Portable artifact contains a duplicate path", path),
      else: :ok
  end

  defp reject_executable_path(path, mode) do
    extension = path |> Path.extname() |> String.downcase()
    executable_mode = is_integer(mode) and band(mode, 0o111) != 0

    if extension in @executable_extensions or executable_mode,
      do: error(:executable_file, "Executable files are not allowed", path),
      else: :ok
  end

  defp reject_executable(path, content) do
    extension = path |> Path.extname() |> String.downcase()

    if extension in @executable_extensions or executable_magic?(content),
      do: error(:executable_file, "Executable files are not allowed", path),
      else: :ok
  end

  defp executable_magic?(<<0x7F, "ELF", _::binary>>), do: true
  defp executable_magic?(<<"MZ", _::binary>>), do: true
  defp executable_magic?(<<"#!", _::binary>>), do: true
  defp executable_magic?(_content), do: false

  defp extract(kind, binary) do
    root = @roots[kind]

    case :zip.extract(binary, [:memory]) do
      {:ok, entries} ->
        Enum.reduce_while(entries, {:ok, %{}}, fn {raw_name, content}, {:ok, files} ->
          with {:ok, full_path} <- normalize_archive_path(kind, raw_name) do
            relative = String.replace_prefix(full_path, root, "")

            if relative == "" or String.ends_with?(relative, "/") do
              {:cont, {:ok, files}}
            else
              {:cont, {:ok, Map.put(files, relative, IO.iodata_to_binary(content))}}
            end
          else
            {:error, _reason} = error -> {:halt, error}
          end
        end)

      {:error, reason} ->
        error(:invalid_archive, "Portable artifact could not be decompressed", reason)
    end
  rescue
    exception -> error(:invalid_archive, "Portable artifact could not be decompressed", exception)
  catch
    kind, reason ->
      error(:invalid_archive, "Portable artifact could not be decompressed", {kind, reason})
  end

  defp validate_extracted_files(files) do
    total = Enum.reduce(files, 0, fn {_path, content}, acc -> acc + byte_size(content) end)

    cond do
      total > @max_uncompressed_bytes ->
        error(:archive_too_large, "Uncompressed portable artifact exceeds the 64 MB limit")

      Enum.any?(files, fn {_path, content} -> byte_size(content) > @max_file_bytes end) ->
        error(:file_too_large, "A portable artifact file exceeds the 32 MB limit")

      Enum.any?(files, fn {path, content} ->
        match?({:error, _}, reject_executable(path, content))
      end) ->
        error(:executable_file, "Executable file content is not allowed")

      true ->
        :ok
    end
  end

  defp parse_manifest(files) do
    case files["manifest.json"] do
      content when is_binary(content) ->
        case Jason.decode(content) do
          {:ok, manifest} when is_map(manifest) -> {:ok, stringify_keys(manifest)}
          _ -> error(:invalid_manifest, "manifest.json must contain a JSON object")
        end

      _ ->
        error(:missing_manifest, "Portable artifact is missing manifest.json")
    end
  end

  defp validate_manifest(kind, manifest, files) do
    declared = manifest["files"]
    payload_files = Map.delete(files, "manifest.json")

    cond do
      manifest["format"] != @formats[kind] ->
        error(:format_mismatch, "Portable artifact format does not match its file extension")

      not is_map(declared) ->
        error(:invalid_manifest, "Portable artifact manifest must declare file hashes")

      Enum.sort(Map.keys(declared)) != Enum.sort(Map.keys(payload_files)) ->
        error(:file_manifest_mismatch, "Portable artifact files do not match its manifest")

      true ->
        with :ok <- validate_declared_hashes(declared, payload_files),
             expected <- manifest |> Map.delete("content_hash") |> ContentHash.digest(),
             true <- manifest["content_hash"] == expected do
          :ok
        else
          {:error, _reason} = error -> error
          _ -> error(:content_hash_mismatch, "Portable artifact manifest hash does not match")
        end
    end
  end

  defp validate_declared_hashes(declared, files) do
    Enum.reduce_while(declared, :ok, fn {path, hash}, :ok ->
      expected = files[path]
      normalized = if is_binary(hash), do: String.replace_prefix(hash, "sha256:", ""), else: ""

      if is_binary(expected) and normalized == sha256(expected),
        do: {:cont, :ok},
        else: {:halt, error(:hash_mismatch, "Portable artifact file hash does not match", path)}
    end)
  end

  defp create_zip(kind, files) do
    root = @roots[kind]

    entries =
      files
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {relative, content} ->
        path = String.to_charlist(root <> relative)

        stat =
          %File.Stat{
            size: byte_size(content),
            type: :regular,
            access: :read_write,
            atime: @fixed_zip_time,
            mtime: @fixed_zip_time,
            ctime: @fixed_zip_time,
            mode: 0o644,
            links: 1,
            major_device: 0,
            minor_device: 0,
            inode: 0,
            uid: 0,
            gid: 0
          }
          |> File.Stat.to_record()

        {path, content, stat}
      end)

    case :zip.create(~c"hydra-portable.zip", entries, [:memory]) do
      {:ok, {_name, binary}} -> {:ok, binary}
      {:error, reason} -> error(:export_failed, "Portable artifact could not be created", reason)
    end
  end

  defp sha256(content), do: :crypto.hash(:sha256, content) |> Base.encode16(case: :lower)

  defp stringify_keys(value) when is_map(value),
    do: Map.new(value, fn {key, nested} -> {to_string(key), stringify_keys(nested)} end)

  defp stringify_keys(value) when is_list(value), do: Enum.map(value, &stringify_keys/1)
  defp stringify_keys(value), do: value

  defp error(code, message, detail \\ nil),
    do: {:error, %{code: code, message: message, detail: detail}}
end
