defmodule HydraAgentWeb.BlueprintCopy do
  @moduledoc "English and Russian interface copy for the Blueprint library."

  @copy %{
    "en" => %{
      nav_simulations: "Simulations",
      nav_blueprints: "Blueprints",
      nav_settings: "Settings",
      nav_operations: "Operations",
      nav_sign_out: "Sign out",
      global_nav: "Global navigation",
      brand_home: "Hydra home",
      account_settings_for: "Account settings for %{name}",
      skip: "Skip to content",
      library_eyebrow: "Blueprint library",
      library_title: "How Hydra builds a simulation",
      library_lede:
        "Blueprints keep research, agents, simulation rules, and reporting portable and inspectable.",
      workspace: "Workspace",
      switch: "Switch",
      built_in: "Built in",
      custom: "Workspace",
      read_only: "Read-only source",
      version: "Version",
      open: "Open",
      duplicate: "Duplicate",
      edit: "Edit",
      test: "Test Blueprint",
      export: "Export package",
      import_title: "Import a Blueprint",
      import_lede:
        "Only declarative .hydra-blueprint packages are accepted. Files are inspected before extraction.",
      choose_file: "Choose package",
      no_file: "No package selected",
      import: "Import",
      no_workspace_title: "A workspace is required",
      no_workspace_lede:
        "Create or join a workspace before saving, duplicating, or importing Blueprints.",
      empty_title: "No workspace Blueprints yet",
      empty_lede: "Duplicate one of the two built-ins to create an editable version.",
      back_library: "Blueprint library",
      validated: "Validated",
      content_hash: "Content hash",
      four_modules: "Four instruction modules",
      modules_lede: "Each stage has a narrow responsibility and a schema-validated output.",
      research: "Context & research",
      agents: "Agents",
      simulation: "Simulation",
      report: "Report",
      research_hint: "Collect only the evidence needed to model the question.",
      agents_hint: "Define a structured population without writing one biography per agent.",
      simulation_hint: "Generate bounded, declarative rules with no executable code.",
      report_hint: "Interpret validated analysis with traceable claims.",
      instructions: "Instructions",
      expected_output: "Expected output",
      sample_output: "Generate sample",
      sample_note: "Stored miniature example · no provider call",
      advanced: "Advanced contract",
      manifest: "Manifest",
      immutable_history: "Immutable version history",
      edit_title: "Refine the method",
      edit_lede:
        "Saving creates a new immutable version. Existing simulations continue to reference the version they used.",
      new_version: "New semantic version",
      version_hint: "Must be higher than the active version.",
      restore_default: "Restore built-in default",
      restored: "Built-in instructions restored. Save to publish the new version.",
      raw_yaml: "Raw manifest YAML",
      raw_yaml_hint: "Advanced settings are validated before anything is saved.",
      save_version: "Save new version",
      cancel: "Cancel",
      test_result: "Blueprint Test",
      passed: "Passed",
      failed: "Needs attention",
      not_published: "Tested only · no version published",
      miniature: "3 agents · 2 rounds",
      provider_calls: "provider calls",
      warnings: "Warnings",
      failures: "Validation failures",
      no_warnings: "No warnings",
      no_failures: "No failures",
      package_structure: "Package structure",
      cost: "Cost",
      locale_label: "Language",
      english: "EN",
      russian: "RU",
      imported_ok: "Blueprint imported.",
      duplicated_ok: "Editable Blueprint created.",
      saved_ok: "New Blueprint version saved.",
      invalid_package: "The package was rejected. Check its structure and safety requirements.",
      import_disabled: "Blueprint import is unavailable on this installation.",
      forbidden: "You do not have permission to change Blueprints in this workspace.",
      read_only_notice: "Built-ins stay pristine. Duplicate this Blueprint to edit it.",
      validation_error: "Nothing was saved. Review the highlighted contract and try again.",
      file_required: "Choose a .hydra-blueprint package to import.",
      locale_changed: "Language changed"
    },
    "ru" => %{
      nav_simulations: "Симуляции",
      nav_blueprints: "Шаблоны",
      nav_settings: "Настройки",
      nav_operations: "Операции",
      nav_sign_out: "Выйти",
      global_nav: "Основная навигация",
      brand_home: "Главная Hydra",
      account_settings_for: "Настройки аккаунта: %{name}",
      skip: "Перейти к содержимому",
      library_eyebrow: "Библиотека шаблонов",
      library_title: "Как Hydra строит симуляцию",
      library_lede:
        "Шаблоны делают исследование, агентов, правила симуляции и отчёт переносимыми и проверяемыми.",
      workspace: "Рабочее пространство",
      switch: "Открыть",
      built_in: "Встроенный",
      custom: "Рабочий",
      read_only: "Только для чтения",
      version: "Версия",
      open: "Открыть",
      duplicate: "Дублировать",
      edit: "Редактировать",
      test: "Проверить шаблон",
      export: "Экспортировать пакет",
      import_title: "Импорт шаблона",
      import_lede:
        "Принимаются только декларативные пакеты .hydra-blueprint. Файлы проверяются до распаковки.",
      choose_file: "Выбрать пакет",
      no_file: "Пакет не выбран",
      import: "Импортировать",
      no_workspace_title: "Нужно рабочее пространство",
      no_workspace_lede:
        "Создайте рабочее пространство или присоединитесь к нему, чтобы сохранять, дублировать и импортировать шаблоны.",
      empty_title: "Рабочих шаблонов пока нет",
      empty_lede:
        "Дублируйте один из двух встроенных шаблонов, чтобы создать редактируемую версию.",
      back_library: "Библиотека шаблонов",
      validated: "Проверен",
      content_hash: "Хеш содержимого",
      four_modules: "Четыре модуля инструкций",
      modules_lede: "У каждого этапа одна задача и результат, проверяемый по схеме.",
      research: "Контекст и исследование",
      agents: "Агенты",
      simulation: "Симуляция",
      report: "Отчёт",
      research_hint: "Собирает только те данные, которые нужны для моделирования вопроса.",
      agents_hint: "Задаёт структурированную популяцию без биографии для каждого агента.",
      simulation_hint: "Создаёт ограниченные декларативные правила без исполняемого кода.",
      report_hint: "Интерпретирует проверенный анализ и сохраняет ссылки на основания.",
      instructions: "Инструкции",
      expected_output: "Ожидаемый результат",
      sample_output: "Создать пример",
      sample_note: "Сохранённый мини-пример · без обращения к провайдеру",
      advanced: "Расширенный контракт",
      manifest: "Манифест",
      immutable_history: "Неизменяемая история версий",
      edit_title: "Уточните метод",
      edit_lede:
        "Сохранение создаёт новую неизменяемую версию. Существующие симуляции продолжают ссылаться на использованную версию.",
      new_version: "Новая семантическая версия",
      version_hint: "Должна быть выше активной версии.",
      restore_default: "Вернуть встроенные инструкции",
      restored: "Встроенные инструкции восстановлены. Сохраните новую версию.",
      raw_yaml: "Исходный YAML манифеста",
      raw_yaml_hint: "Расширенные настройки проверяются до сохранения.",
      save_version: "Сохранить новую версию",
      cancel: "Отмена",
      test_result: "Проверка шаблона",
      passed: "Пройдено",
      failed: "Нужно исправить",
      not_published: "Только проверка · версия не опубликована",
      miniature: "3 агента · 2 раунда",
      provider_calls: "обращений к провайдеру",
      warnings: "Предупреждения",
      failures: "Ошибки проверки",
      no_warnings: "Предупреждений нет",
      no_failures: "Ошибок нет",
      package_structure: "Структура пакета",
      cost: "Стоимость",
      locale_label: "Язык",
      english: "EN",
      russian: "RU",
      imported_ok: "Шаблон импортирован.",
      duplicated_ok: "Редактируемый шаблон создан.",
      saved_ok: "Новая версия шаблона сохранена.",
      invalid_package: "Пакет отклонён. Проверьте его структуру и требования безопасности.",
      import_disabled: "Импорт шаблонов недоступен в этой установке.",
      forbidden: "У вас нет прав на изменение шаблонов в этом рабочем пространстве.",
      read_only_notice: "Встроенные шаблоны неизменяемы. Создайте копию для редактирования.",
      validation_error: "Ничего не сохранено. Проверьте контракт и повторите попытку.",
      file_required: "Выберите пакет .hydra-blueprint для импорта.",
      locale_changed: "Язык изменён"
    }
  }

  def t(locale, key) do
    locale = if locale in ["en", "ru"], do: locale, else: "en"
    get_in(@copy, [locale, key]) || get_in(@copy, ["en", key]) || to_string(key)
  end

  def account_settings_label(locale, name) do
    locale
    |> t(:account_settings_for)
    |> String.replace("%{name}", name)
  end
end
