defmodule HydraAgentWeb.SimulationCopy do
  @moduledoc "English and Russian interface copy for Simulation Studio."

  @copy %{
    "en" => %{
      locale_label: "Language",
      english: "EN",
      russian: "RU",
      workspace: "Workspace",
      switch: "Switch",
      simulations: "Simulations",
      index_eyebrow: "Simulation Studio",
      index_title: "Simulations",
      index_lede:
        "Each simulation keeps its question, Blueprint, inputs, and build state together.",
      new_simulation: "New simulation",
      no_simulations: "No simulations yet",
      no_simulations_lede: "Start with one question. Files, URLs, and settings are optional.",
      no_workspace: "A workspace is required",
      no_workspace_lede: "Create or join a workspace before starting a simulation.",
      stage: "Stage",
      blueprint: "Blueprint",
      population: "Population",
      updated: "Updated",
      open: "Open",
      duplicate: "Duplicate",
      archive: "Archive",
      legacy: "Previous SimLab study",
      legacy_lede: "Preserved in the original, inspectable workflow.",
      describe: "Describe",
      compose_title: "What world or decision do you want to simulate?",
      compose_lede:
        "Start with the question. Hydra saves a durable draft before any provider is called.",
      question: "Simulation question",
      question_placeholder:
        "How might employees respond to mandatory AI monitoring over one quarter?",
      title_optional: "Title · optional",
      title_placeholder: "Hydra will derive a concise title from the question",
      choose_blueprint: "Choose a method",
      blueprint_hint:
        "The Blueprint controls how context, agents, rules, and the report are built.",
      choose_mode: "Execution mode",
      quick: "Quick",
      balanced: "Balanced",
      deep: "Deep",
      quick_hint: "Deterministic execution · zero model decisions during the run",
      balanced_hint: "Selective model reasoning under a hard decision cap",
      deep_hint: "Experimental · model-intensive and tightly capped",
      unavailable: "Unavailable",
      optional_context: "Optional context",
      optional_context_hint: "Everything below can be added later.",
      notes: "Notes or pasted data",
      notes_placeholder: "Add relevant constraints, observations, or structured text.",
      urls: "Public HTTPS URLs",
      urls_placeholder: "One URL per line",
      urls_hint: "Saved now; validated and fetched only during Build.",
      files: "Files or data",
      files_hint: "Up to 5 UTF-8 TXT, Markdown, CSV, or JSON files · 2 MB total",
      geography: "Geography · optional",
      geography_placeholder: "For example: Germany",
      horizon: "Time horizon · optional",
      horizon_placeholder: "For example: one quarter",
      population_size: "Population size",
      population_hint: "A structured population, not a respondent sample.",
      defaults_disclosure: "Quick research · automatic models · quick budget",
      continue_build: "Continue to Build",
      cancel: "Cancel",
      invalid_form: "Nothing was saved. Review the question and optional inputs.",
      invalid_url: "Use public HTTPS URLs without credentials or IP addresses.",
      invalid_file: "Use up to five valid UTF-8 TXT, Markdown, CSV, or JSON files.",
      mode_disabled: "That execution mode is not enabled on this installation.",
      created: "Simulation draft saved.",
      duplicated: "Simulation draft duplicated.",
      archived: "Simulation archived.",
      back: "All simulations",
      draft: "Draft",
      building: "Building",
      needs_attention: "Needs attention",
      ready_to_run: "Ready to run",
      running: "Running",
      analyzing: "Analyzing",
      ready: "Ready",
      failed: "Failed",
      canceled: "Canceled",
      archived_status: "Archived",
      build: "Build",
      run: "Run",
      explore: "Explore",
      compare: "Compare",
      current_stage: "Current stage",
      build_title: "Build the world",
      build_lede:
        "Hydra keeps each completed step durable, versioned, and safe to resume after refresh.",
      build_not_started: "Build not started",
      build_not_started_lede:
        "Your question and inputs are saved. No provider has been called and no Pack is marked ready.",
      inputs_saved: "Inputs saved",
      no_inputs: "Question only",
      file_count: "%{count} files",
      url_count: "%{count} URLs",
      notes_added: "Notes added",
      understanding_question: "Understanding the question",
      finding_context: "Finding useful context",
      designing_population: "Designing the population",
      writing_rules: "Writing the simulation rules",
      checking_model: "Checking the model",
      preparing_run: "Preparing the run",
      pending: "Waiting",
      complete: "Complete",
      partial: "Partial",
      running_stage: "In progress",
      failed_stage: "Needs attention",
      superseded: "Superseded",
      modules_eyebrow: "Blueprint instructions",
      modules_title: "Four narrow responsibilities",
      modules_lede: "Each stage has a schema-validated output and can be inspected before a run.",
      context: "Context",
      agents: "Agents",
      simulation: "Simulation",
      report: "Report",
      context_summary: "Collect only the evidence needed to model this question.",
      agents_summary: "Define a structured population and its meaningful differences.",
      simulation_summary: "Create bounded declarative actions, state, events, and time.",
      report_summary: "Interpret validated analysis with traceable references.",
      inspect_details: "Inspect details",
      inspect_blueprint: "Inspect Blueprint",
      edit_instructions: "Edit instructions",
      selected_method: "Selected method",
      exact_version: "Exact version",
      content_hash: "Content hash",
      build_inputs: "Build inputs",
      question_only: "No optional evidence attached",
      run_title: "Run checkpoint",
      not_ready_to_run: "Not ready to run",
      not_ready_to_run_lede:
        "Finish Build first. Hydra will not execute an incomplete or unvalidated Simulation Pack.",
      run_simulation: "Run simulation",
      edit_build: "Return to Build",
      ready_summary: "Ready-to-run summary",
      agent_types: "Agent types",
      rounds: "Rounds",
      actions: "Actions",
      resources: "Resources",
      events: "Scheduled events",
      mode: "Reasoning",
      max_cost: "Maximum provider cost",
      max_decisions: "Maximum model decisions",
      not_estimated: "Not estimated",
      not_built: "Not built",
      deterministic: "Deterministic",
      results_title: "Explore results",
      results_empty: "Results will appear after a completed run.",
      results_empty_lede:
        "State, Flow, and Explain remain locked until the Run Record and Analysis Pack exist.",
      compare_title: "Compare runs",
      compare_runs: "Compare runs",
      compare_empty: "Run at least two compatible scenarios before comparing them.",
      compare_empty_lede:
        "Hydra will keep Pack versions, seeds, modes, and model decisions explicit.",
      locked: "Locked",
      provider_calls: "Provider calls",
      zero: "0",
      not_sample: "Synthetic population · not a respondent sample"
    },
    "ru" => %{
      locale_label: "Язык",
      english: "EN",
      russian: "RU",
      workspace: "Рабочее пространство",
      switch: "Открыть",
      simulations: "Симуляции",
      index_eyebrow: "Студия симуляций",
      index_title: "Симуляции",
      index_lede:
        "Каждая симуляция хранит вопрос, шаблон, исходные данные и состояние сборки вместе.",
      new_simulation: "Новая симуляция",
      no_simulations: "Симуляций пока нет",
      no_simulations_lede: "Начните с одного вопроса. Файлы, ссылки и настройки необязательны.",
      no_workspace: "Нужно рабочее пространство",
      no_workspace_lede: "Создайте рабочее пространство или присоединитесь к нему.",
      stage: "Этап",
      blueprint: "Шаблон",
      population: "Популяция",
      updated: "Обновлено",
      open: "Открыть",
      duplicate: "Дублировать",
      archive: "Архивировать",
      legacy: "Предыдущая симуляция SimLab",
      legacy_lede: "Сохранена в исходном проверяемом процессе.",
      describe: "Описание",
      compose_title: "Какой мир или решение вы хотите смоделировать?",
      compose_lede:
        "Начните с вопроса. Hydra сохранит черновик до любого обращения к провайдеру.",
      question: "Вопрос симуляции",
      question_placeholder:
        "Как сотрудники могут отреагировать на обязательный ИИ-мониторинг за один квартал?",
      title_optional: "Название · необязательно",
      title_placeholder: "Hydra создаст краткое название из вопроса",
      choose_blueprint: "Выберите метод",
      blueprint_hint: "Шаблон определяет, как строятся контекст, агенты, правила и отчёт.",
      choose_mode: "Режим выполнения",
      quick: "Быстрый",
      balanced: "Сбалансированный",
      deep: "Глубокий",
      quick_hint: "Детерминированное выполнение · без модельных решений в ходе запуска",
      balanced_hint: "Выборочные модельные решения с жёстким лимитом",
      deep_hint: "Экспериментальный · интенсивное и строго ограниченное использование модели",
      unavailable: "Недоступно",
      optional_context: "Дополнительный контекст",
      optional_context_hint: "Всё ниже можно добавить позднее.",
      notes: "Заметки или вставленные данные",
      notes_placeholder: "Добавьте ограничения, наблюдения или структурированный текст.",
      urls: "Публичные HTTPS-ссылки",
      urls_placeholder: "Одна ссылка на строку",
      urls_hint: "Сохраняются сейчас; проверяются и загружаются только на этапе сборки.",
      files: "Файлы или данные",
      files_hint: "До 5 файлов UTF-8 TXT, Markdown, CSV или JSON · всего 2 МБ",
      geography: "География · необязательно",
      geography_placeholder: "Например: Германия",
      horizon: "Временной горизонт · необязательно",
      horizon_placeholder: "Например: один квартал",
      population_size: "Размер популяции",
      population_hint: "Структурированная популяция, а не выборка респондентов.",
      defaults_disclosure: "Быстрое исследование · автоматические модели · быстрый бюджет",
      continue_build: "Перейти к сборке",
      cancel: "Отмена",
      invalid_form: "Ничего не сохранено. Проверьте вопрос и дополнительные данные.",
      invalid_url: "Используйте публичные HTTPS-ссылки без учётных данных и IP-адресов.",
      invalid_file: "Используйте до пяти корректных файлов UTF-8 TXT, Markdown, CSV или JSON.",
      mode_disabled: "Этот режим выполнения не включён в данной установке.",
      created: "Черновик симуляции сохранён.",
      duplicated: "Черновик симуляции дублирован.",
      archived: "Симуляция архивирована.",
      back: "Все симуляции",
      draft: "Черновик",
      building: "Сборка",
      needs_attention: "Нужно исправить",
      ready_to_run: "Готово к запуску",
      running: "Выполняется",
      analyzing: "Анализ",
      ready: "Готово",
      failed: "Ошибка",
      canceled: "Отменено",
      archived_status: "В архиве",
      build: "Сборка",
      run: "Запуск",
      explore: "Результаты",
      compare: "Сравнение",
      current_stage: "Текущий этап",
      build_title: "Соберите мир",
      build_lede:
        "Hydra сохраняет каждый завершённый шаг, версию и возможность продолжить после обновления страницы.",
      build_not_started: "Сборка не начата",
      build_not_started_lede:
        "Вопрос и данные сохранены. Обращений к провайдеру не было, пакет не отмечен готовым.",
      inputs_saved: "Данные сохранены",
      no_inputs: "Только вопрос",
      file_count: "%{count} файлов",
      url_count: "%{count} ссылок",
      notes_added: "Заметки добавлены",
      understanding_question: "Понимание вопроса",
      finding_context: "Поиск полезного контекста",
      designing_population: "Проектирование популяции",
      writing_rules: "Создание правил симуляции",
      checking_model: "Проверка модели",
      preparing_run: "Подготовка запуска",
      pending: "Ожидает",
      complete: "Готово",
      partial: "Частично",
      running_stage: "Выполняется",
      failed_stage: "Нужно исправить",
      superseded: "Заменено",
      modules_eyebrow: "Инструкции шаблона",
      modules_title: "Четыре узкие задачи",
      modules_lede: "У каждого этапа есть проверяемый результат, доступный до запуска.",
      context: "Контекст",
      agents: "Агенты",
      simulation: "Симуляция",
      report: "Отчёт",
      context_summary: "Собрать только те данные, которые нужны для моделирования вопроса.",
      agents_summary: "Задать структурированную популяцию и значимые различия.",
      simulation_summary:
        "Создать ограниченные декларативные действия, состояния, события и время.",
      report_summary: "Интерпретировать проверенный анализ с прослеживаемыми ссылками.",
      inspect_details: "Подробнее",
      inspect_blueprint: "Открыть шаблон",
      edit_instructions: "Изменить инструкции",
      selected_method: "Выбранный метод",
      exact_version: "Точная версия",
      content_hash: "Хеш содержимого",
      build_inputs: "Исходные данные сборки",
      question_only: "Дополнительные данные не приложены",
      run_title: "Контрольная точка запуска",
      not_ready_to_run: "Не готово к запуску",
      not_ready_to_run_lede:
        "Сначала завершите сборку. Hydra не запустит неполный или непроверенный пакет симуляции.",
      run_simulation: "Запустить симуляцию",
      edit_build: "Вернуться к сборке",
      ready_summary: "Сводка перед запуском",
      agent_types: "Типы агентов",
      rounds: "Раунды",
      actions: "Действия",
      resources: "Ресурсы",
      events: "Запланированные события",
      mode: "Рассуждение",
      max_cost: "Максимальная стоимость провайдера",
      max_decisions: "Максимум модельных решений",
      not_estimated: "Не рассчитано",
      not_built: "Не построено",
      deterministic: "Детерминированный",
      results_title: "Изучение результатов",
      results_empty: "Результаты появятся после завершённого запуска.",
      results_empty_lede:
        "Состояние, потоки и объяснения недоступны до появления записи запуска и пакета анализа.",
      compare_title: "Сравнение запусков",
      compare_runs: "Сравнить запуски",
      compare_empty: "Для сравнения нужны как минимум два совместимых сценария.",
      compare_empty_lede: "Hydra явно сохранит версии пакетов, seed, режимы и модельные решения.",
      locked: "Недоступно",
      provider_calls: "Обращения к провайдеру",
      zero: "0",
      not_sample: "Синтетическая популяция · не выборка респондентов"
    }
  }

  def t(locale, key) do
    locale = if locale in ["en", "ru"], do: locale, else: "en"
    get_in(@copy, [locale, key]) || get_in(@copy, ["en", key]) || to_string(key)
  end

  def interpolate(locale, key, values) do
    Enum.reduce(values, t(locale, key), fn {name, value}, copy ->
      String.replace(copy, "%{#{name}}", to_string(value))
    end)
  end
end
