defmodule HydraAgentWeb.SimulationCopy do
  @moduledoc "English and Russian interface copy for Simulation Studio."

  @copy %{
    "en" => %{
      locale_label: "Language",
      english: "EN",
      russian: "RU",
      workspace: "Workspace",
      switch: "Switch",
      simulations: "Simulations",
      index_eyebrow: "Simulation Studio",
      index_title: "Simulations",
      index_lede:
        "Each simulation keeps its question, Blueprint, inputs, and build state together.",
      new_simulation: "New simulation",
      no_simulations: "No simulations yet",
      no_simulations_lede: "Start with one question. Files, URLs, and settings are optional.",
      no_workspace: "A workspace is required",
      no_workspace_lede: "Create or join a workspace before starting a simulation.",
      stage: "Stage",
      blueprint: "Blueprint",
      population: "Population",
      updated: "Updated",
      open: "Open",
      duplicate: "Duplicate",
      archive: "Archive",
      legacy: "Previous SimLab study",
      legacy_lede: "Preserved in the original, inspectable workflow.",
      describe: "Describe",
      compose_title: "What world or decision do you want to simulate?",
      compose_lede:
        "Start with the question. Hydra saves it first, then builds a visible Context Pack.",
      question: "Simulation question",
      question_placeholder:
        "How might employees respond to mandatory AI monitoring over one quarter?",
      title_optional: "Title · optional",
      title_placeholder: "Hydra will derive a concise title from the question",
      choose_blueprint: "Choose a method",
      blueprint_hint:
        "The Blueprint controls how context, agents, rules, and the report are built.",
      choose_mode: "Execution mode",
      quick: "Quick",
      balanced: "Balanced",
      deep: "Deep",
      quick_hint: "Deterministic execution · zero model decisions during the run",
      balanced_hint: "Selective model reasoning under a hard decision cap",
      deep_hint: "Experimental · model-intensive and tightly capped",
      unavailable: "Unavailable",
      optional_context: "Optional context",
      optional_context_hint: "Everything below can be added later.",
      notes: "Notes or pasted data",
      notes_placeholder: "Add relevant constraints, observations, or structured text.",
      urls: "Public HTTPS URLs",
      urls_placeholder: "One URL per line",
      urls_hint: "Saved now; validated and fetched only during Build.",
      files: "Files or data",
      files_hint: "Up to 5 UTF-8 TXT, Markdown, CSV, or JSON files · 2 MB total",
      geography: "Geography · optional",
      geography_placeholder: "For example: Germany",
      horizon: "Time horizon · optional",
      horizon_placeholder: "For example: one quarter",
      historical_cutoff: "Historical cutoff · optional",
      historical_cutoff_hint: "Sources published later will be excluded.",
      population_size: "Population size",
      population_hint: "A structured population, not a respondent sample.",
      defaults_disclosure: "Quick research · automatic models · quick budget",
      continue_build: "Continue to Build",
      cancel: "Cancel",
      invalid_form: "Nothing was saved. Review the question and optional inputs.",
      invalid_url: "Use public HTTPS URLs without credentials or IP addresses.",
      invalid_file: "Use up to five valid UTF-8 TXT, Markdown, CSV, or JSON files.",
      invalid_cutoff: "Use a valid historical cutoff date.",
      mode_disabled: "That execution mode is not enabled on this installation.",
      created: "Simulation created. Context is ready to inspect.",
      duplicated: "Simulation duplicated. Context is ready to inspect.",
      archived: "Simulation archived.",
      back: "All simulations",
      draft: "Draft",
      building: "Building",
      needs_attention: "Needs attention",
      ready_to_run: "Ready to run",
      running: "Running",
      analyzing: "Analyzing",
      ready: "Ready",
      failed: "Failed",
      canceled: "Canceled",
      archived_status: "Archived",
      build: "Build",
      run: "Run",
      explore: "Explore",
      compare: "Compare",
      current_stage: "Current stage",
      build_title: "Build the world",
      build_lede:
        "Hydra keeps each completed step durable, versioned, and safe to resume after refresh.",
      build_not_started: "Build not started",
      build_not_started_lede:
        "Your question and inputs are saved. No provider has been called and no Pack is marked ready.",
      inputs_saved: "Inputs saved",
      no_inputs: "Question only",
      file_count: "%{count} files",
      url_count: "%{count} URLs",
      notes_added: "Notes added",
      understanding_question: "Understanding the question",
      finding_context: "Finding useful context",
      designing_population: "Designing the population",
      writing_rules: "Writing the simulation rules",
      checking_model: "Checking the model",
      preparing_run: "Preparing the run",
      pending: "Waiting",
      complete: "Complete",
      partial: "Partial",
      running_stage: "In progress",
      failed_stage: "Needs attention",
      superseded: "Superseded",
      modules_eyebrow: "Blueprint instructions",
      modules_title: "Four narrow responsibilities",
      modules_lede: "Each stage has a schema-validated output and can be inspected before a run.",
      context: "Context",
      agents: "Agents",
      simulation: "Simulation",
      report: "Report",
      context_summary: "Collect only the evidence needed to model this question.",
      agents_summary: "Define a structured population and its meaningful differences.",
      simulation_summary: "Create bounded declarative actions, state, events, and time.",
      report_summary: "Interpret validated analysis with traceable references.",
      inspect_details: "Inspect details",
      inspect_blueprint: "Inspect Blueprint",
      edit_instructions: "Edit instructions",
      selected_method: "Selected method",
      exact_version: "Exact version",
      content_hash: "Content hash",
      build_inputs: "Build inputs",
      question_only: "No optional evidence attached",
      run_title: "Run checkpoint",
      not_ready_to_run: "Not ready to run",
      not_ready_to_run_lede:
        "Finish Build first. Hydra will not execute an incomplete or unvalidated Simulation Pack.",
      run_simulation: "Run simulation",
      edit_build: "Return to Build",
      ready_summary: "Ready-to-run summary",
      agent_types: "Agent types",
      rounds: "Rounds",
      actions: "Actions",
      resources: "Resources",
      events: "Scheduled events",
      mode: "Reasoning",
      max_cost: "Maximum provider cost",
      max_decisions: "Maximum model decisions",
      not_estimated: "Not estimated",
      not_built: "Not built",
      deterministic: "Deterministic",
      results_title: "Explore results",
      results_empty: "Results will appear after a completed run.",
      results_empty_lede:
        "State, Flow, and Explain remain locked until the Run Record and Analysis Pack exist.",
      compare_title: "Compare runs",
      compare_runs: "Compare runs",
      compare_empty: "Run at least two compatible scenarios before comparing them.",
      compare_empty_lede:
        "Hydra will keep Pack versions, seeds, modes, and model decisions explicit.",
      locked: "Locked",
      provider_calls: "Retrieval requests",
      zero: "0",
      not_sample: "Synthetic population · not a respondent sample",
      context_pack: "Context Pack",
      context_title: "Context and assumptions",
      context_lede:
        "Inspect what is sourced, what is only a prior, and what Hydra still has to assume.",
      context_ready: "Context ready",
      context_partial: "Context is usable with gaps",
      context_ready_lede:
        "Context Pack v%{version} · %{claims} claims · %{assumptions} assumptions",
      inspect_context: "Inspect context",
      assemble_context: "Assemble context",
      context_assembled: "The Context Pack is active.",
      context_research_queued: "Bounded web context is queued.",
      context_research_not_configured:
        "Web context is not connected. The current Pack remains usable with visible assumptions.",
      context_source_excluded: "Source excluded. A new Context Pack version is active.",
      context_version: "Pack version",
      context_confidence: "Confidence",
      context_confidence_low: "Low",
      context_confidence_moderate: "Moderate",
      context_confidence_high: "High",
      context_sources: "Sources",
      context_claims: "Claims",
      context_assumptions: "Assumptions",
      context_gaps: "Open gaps",
      context_scope: "Scope",
      context_world: "Interpreted world",
      context_geography: "Geography",
      context_horizon: "Time horizon",
      context_agent_types: "Candidate agent types",
      context_resources: "Candidate resources",
      context_actions: "Candidate actions",
      context_cutoff: "Historical cutoff",
      context_no_cutoff: "No cutoff",
      context_no_sources: "No active sources yet.",
      context_no_claims: "No sourced claims yet.",
      context_no_gaps: "No material context gaps recorded.",
      context_source_pending: "Pending retrieval",
      context_source_active: "Active",
      context_source_review: "Review required",
      context_exclude_source: "Exclude source",
      context_exclude_source_named: "Exclude %{source}",
      context_published: "Published %{date}",
      context_claim_source: "Source · %{source}",
      context_add_web: "Add bounded web context",
      context_web_unavailable: "Web context not connected",
      context_research_running: "Research in progress",
      context_research_completed: "Research complete",
      context_research_failed: "Research needs attention",
      context_research_queued_status: "Research queued",
      context_research_plan: "Research plan",
      context_show_query: "Show retrieval query",
      context_provider_calls: "%{count} retrieval requests",
      context_grounding_user_data: "User data",
      context_grounding_user_document: "User document",
      context_grounding_external_source: "External source",
      context_grounding_analogue: "Analogue",
      context_grounding_model_prior: "Model prior",
      context_grounding_assumption: "Assumption",
      context_gap_sourced_evidence: "Sourced evidence",
      context_gap_pending_sources: "Pending sources",
      context_gap_failed_research_lane: "Failed research lane",
      context_gap_historical_cutoff: "Historical cutoff",
      context_gap_source_excluded: "Excluded source",
      context_gap_source_retrieval_failed: "Unavailable source",
      context_gap_research_not_run: "Research not run",
      context_return_build: "Return to Build",
      population_title: "Population model",
      population_lede:
        "Inspect the structured differences Hydra will instantiate—not a warehouse of synthetic biographies.",
      population_build_action: "Build population",
      population_rebuild_action: "Rebuild from current context",
      population_built: "The Population Model is active.",
      population_ready: "Population structure is ready",
      population_partial: "Population is usable with import notes",
      population_version: "Model version",
      population_agents: "Modeled agents",
      population_generated: "Generated",
      population_imported_count: "Imported",
      population_relationships: "Relationships",
      population_seed: "Seed",
      population_compiler: "Compiler",
      population_types: "Agent types",
      population_archetypes: "Archetypes",
      population_attributes: "Attributes",
      population_actions: "Available actions",
      population_resources: "Initial resources",
      population_grounding: "Grounding links",
      population_agents_count: "%{count} agents",
      population_remove_attribute: "Remove",
      population_remove_attribute_named: "Remove %{attribute} from %{type} and rebuild",
      population_attribute_removed:
        "Attribute removed. A new Population Model version is active.",
      population_last_attribute: "Each agent type needs at least one attribute.",
      population_sensitive: "Sensitive · aggregate only",
      population_sensitive_source: "Observed and supplied; never inferred for variety.",
      population_sensitive_necessity: "Why it is necessary",
      population_sensitive_lawful_basis: "Lawful basis",
      population_no_sensitive:
        "No protected or sensitive traits were inferred to create variety.",
      population_topology: "Relationship topology",
      population_representatives: "Representatives",
      population_representatives_lede:
        "Readable cards are optional projections of structured state. No prose exists for the full population.",
      population_generate_persona: "Create readable card",
      population_persona_projection: "Readable projection · not authoritative state",
      population_persona_pending: "Structured state only",
      population_structured_state: "Structured state",
      population_goals: "Goals",
      population_constraints: "Constraints",
      population_current_state: "Current state",
      population_important_relationships: "Important relationships",
      population_grounding_count: "%{count} grounding links",
      persona_generated: "Readable representative card created.",
      population_import: "Import structured population",
      population_import_lede:
        "Use CSV or JSON. Valid rows continue; invalid rows are reported without exposing their values.",
      population_import_kind: "Import kind",
      population_import_agents: "Agents",
      population_import_relationships: "Relationship edges",
      population_import_file: "CSV or JSON file",
      population_import_file_hint: "Up to 5 MB · 10,000 agent rows",
      population_id_column: "Agent ID column",
      population_type_column: "Agent type column",
      population_archetype_column: "Archetype column · optional",
      population_attribute_columns: "Attribute columns · optional",
      population_attribute_columns_hint: "Comma separated. Use source:name to rename.",
      population_resource_columns: "Resource columns · optional",
      population_state_columns: "State columns · optional",
      population_agent_mapping: "Agent CSV mapping",
      population_relationship_mapping: "Relationship CSV mapping",
      population_source_column: "Source agent column",
      population_target_column: "Target agent column",
      population_relationship_type_column: "Relationship type column",
      population_weight_column: "Weight column · optional",
      population_directed_column: "Directed column · optional",
      population_import_submit: "Validate and import",
      population_imported: "Valid population rows imported. Review the active model.",
      population_import_failed: "Nothing was imported. Review the file and column mapping.",
      population_import_result: "Latest import",
      population_import_valid: "Valid rows",
      population_import_errors: "Rows needing attention",
      population_import_no_errors: "Every imported row passed validation.",
      population_import_row: "Row %{row}",
      population_import_error_invalid_identifier: "A required identifier is missing or invalid.",
      population_import_error_invalid_object: "The mapped value is not a structured object.",
      population_import_error_sensitive_attribute_requires_model_metadata:
        "A sensitive field needs explicit necessity and lawful-basis metadata in a Population Model JSON file.",
      population_import_error_duplicate_identifier: "An identifier is duplicated.",
      population_import_error_invalid_weight: "A relationship weight must be between 0 and 1.",
      population_import_error_invalid_boolean: "The direction value must be true or false.",
      population_import_error_self_relationship: "A relationship cannot point to the same agent.",
      population_import_error_default: "This row does not match the selected mapping.",
      population_return_build: "Return to Build"
    },
    "ru" => %{
      locale_label: "Язык",
      english: "EN",
      russian: "RU",
      workspace: "Рабочее пространство",
      switch: "Открыть",
      simulations: "Симуляции",
      index_eyebrow: "Студия симуляций",
      index_title: "Симуляции",
      index_lede:
        "Каждая симуляция хранит вопрос, шаблон, исходные данные и состояние сборки вместе.",
      new_simulation: "Новая симуляция",
      no_simulations: "Симуляций пока нет",
      no_simulations_lede: "Начните с одного вопроса. Файлы, ссылки и настройки необязательны.",
      no_workspace: "Нужно рабочее пространство",
      no_workspace_lede: "Создайте рабочее пространство или присоединитесь к нему.",
      stage: "Этап",
      blueprint: "Шаблон",
      population: "Популяция",
      updated: "Обновлено",
      open: "Открыть",
      duplicate: "Дублировать",
      archive: "Архивировать",
      legacy: "Предыдущая симуляция SimLab",
      legacy_lede: "Сохранена в исходном проверяемом процессе.",
      describe: "Описание",
      compose_title: "Какой мир или решение вы хотите смоделировать?",
      compose_lede:
        "Начните с вопроса. Hydra сначала сохранит его, затем соберёт видимый пакет контекста.",
      question: "Вопрос симуляции",
      question_placeholder:
        "Как сотрудники могут отреагировать на обязательный ИИ-мониторинг за один квартал?",
      title_optional: "Название · необязательно",
      title_placeholder: "Hydra создаст краткое название из вопроса",
      choose_blueprint: "Выберите метод",
      blueprint_hint: "Шаблон определяет, как строятся контекст, агенты, правила и отчёт.",
      choose_mode: "Режим выполнения",
      quick: "Быстрый",
      balanced: "Сбалансированный",
      deep: "Глубокий",
      quick_hint: "Детерминированное выполнение · без модельных решений в ходе запуска",
      balanced_hint: "Выборочные модельные решения с жёстким лимитом",
      deep_hint: "Экспериментальный · интенсивное и строго ограниченное использование модели",
      unavailable: "Недоступно",
      optional_context: "Дополнительный контекст",
      optional_context_hint: "Всё ниже можно добавить позднее.",
      notes: "Заметки или вставленные данные",
      notes_placeholder: "Добавьте ограничения, наблюдения или структурированный текст.",
      urls: "Публичные HTTPS-ссылки",
      urls_placeholder: "Одна ссылка на строку",
      urls_hint: "Сохраняются сейчас; проверяются и загружаются только на этапе сборки.",
      files: "Файлы или данные",
      files_hint: "До 5 файлов UTF-8 TXT, Markdown, CSV или JSON · всего 2 МБ",
      geography: "География · необязательно",
      geography_placeholder: "Например: Германия",
      horizon: "Временной горизонт · необязательно",
      horizon_placeholder: "Например: один квартал",
      historical_cutoff: "Историческая отсечка · необязательно",
      historical_cutoff_hint: "Более поздние источники будут исключены.",
      population_size: "Размер популяции",
      population_hint: "Структурированная популяция, а не выборка респондентов.",
      defaults_disclosure: "Быстрое исследование · автоматические модели · быстрый бюджет",
      continue_build: "Перейти к сборке",
      cancel: "Отмена",
      invalid_form: "Ничего не сохранено. Проверьте вопрос и дополнительные данные.",
      invalid_url: "Используйте публичные HTTPS-ссылки без учётных данных и IP-адресов.",
      invalid_file: "Используйте до пяти корректных файлов UTF-8 TXT, Markdown, CSV или JSON.",
      invalid_cutoff: "Укажите корректную дату исторической отсечки.",
      mode_disabled: "Этот режим выполнения не включён в данной установке.",
      created: "Симуляция создана. Контекст готов к проверке.",
      duplicated: "Симуляция дублирована. Контекст готов к проверке.",
      archived: "Симуляция архивирована.",
      back: "Все симуляции",
      draft: "Черновик",
      building: "Сборка",
      needs_attention: "Нужно исправить",
      ready_to_run: "Готово к запуску",
      running: "Выполняется",
      analyzing: "Анализ",
      ready: "Готово",
      failed: "Ошибка",
      canceled: "Отменено",
      archived_status: "В архиве",
      build: "Сборка",
      run: "Запуск",
      explore: "Результаты",
      compare: "Сравнение",
      current_stage: "Текущий этап",
      build_title: "Соберите мир",
      build_lede:
        "Hydra сохраняет каждый завершённый шаг, версию и возможность продолжить после обновления страницы.",
      build_not_started: "Сборка не начата",
      build_not_started_lede:
        "Вопрос и данные сохранены. Обращений к провайдеру не было, пакет не отмечен готовым.",
      inputs_saved: "Данные сохранены",
      no_inputs: "Только вопрос",
      file_count: "%{count} файлов",
      url_count: "%{count} ссылок",
      notes_added: "Заметки добавлены",
      understanding_question: "Понимание вопроса",
      finding_context: "Поиск полезного контекста",
      designing_population: "Проектирование популяции",
      writing_rules: "Создание правил симуляции",
      checking_model: "Проверка модели",
      preparing_run: "Подготовка запуска",
      pending: "Ожидает",
      complete: "Готово",
      partial: "Частично",
      running_stage: "Выполняется",
      failed_stage: "Нужно исправить",
      superseded: "Заменено",
      modules_eyebrow: "Инструкции шаблона",
      modules_title: "Четыре узкие задачи",
      modules_lede: "У каждого этапа есть проверяемый результат, доступный до запуска.",
      context: "Контекст",
      agents: "Агенты",
      simulation: "Симуляция",
      report: "Отчёт",
      context_summary: "Собрать только те данные, которые нужны для моделирования вопроса.",
      agents_summary: "Задать структурированную популяцию и значимые различия.",
      simulation_summary:
        "Создать ограниченные декларативные действия, состояния, события и время.",
      report_summary: "Интерпретировать проверенный анализ с прослеживаемыми ссылками.",
      inspect_details: "Подробнее",
      inspect_blueprint: "Открыть шаблон",
      edit_instructions: "Изменить инструкции",
      selected_method: "Выбранный метод",
      exact_version: "Точная версия",
      content_hash: "Хеш содержимого",
      build_inputs: "Исходные данные сборки",
      question_only: "Дополнительные данные не приложены",
      run_title: "Контрольная точка запуска",
      not_ready_to_run: "Не готово к запуску",
      not_ready_to_run_lede:
        "Сначала завершите сборку. Hydra не запустит неполный или непроверенный пакет симуляции.",
      run_simulation: "Запустить симуляцию",
      edit_build: "Вернуться к сборке",
      ready_summary: "Сводка перед запуском",
      agent_types: "Типы агентов",
      rounds: "Раунды",
      actions: "Действия",
      resources: "Ресурсы",
      events: "Запланированные события",
      mode: "Рассуждение",
      max_cost: "Максимальная стоимость провайдера",
      max_decisions: "Максимум модельных решений",
      not_estimated: "Не рассчитано",
      not_built: "Не построено",
      deterministic: "Детерминированный",
      results_title: "Изучение результатов",
      results_empty: "Результаты появятся после завершённого запуска.",
      results_empty_lede:
        "Состояние, потоки и объяснения недоступны до появления записи запуска и пакета анализа.",
      compare_title: "Сравнение запусков",
      compare_runs: "Сравнить запуски",
      compare_empty: "Для сравнения нужны как минимум два совместимых сценария.",
      compare_empty_lede: "Hydra явно сохранит версии пакетов, seed, режимы и модельные решения.",
      locked: "Недоступно",
      provider_calls: "Запросы к источникам",
      zero: "0",
      not_sample: "Синтетическая популяция · не выборка респондентов",
      context_pack: "Пакет контекста",
      context_title: "Контекст и допущения",
      context_lede: "Проверьте источники, модельные предпосылки и явные допущения Hydra.",
      context_ready: "Контекст готов",
      context_partial: "Контекст пригоден, но есть пробелы",
      context_ready_lede:
        "Пакет v%{version} · утверждений: %{claims} · допущений: %{assumptions}",
      inspect_context: "Открыть контекст",
      assemble_context: "Собрать контекст",
      context_assembled: "Пакет контекста активен.",
      context_research_queued: "Ограниченный веб-поиск поставлен в очередь.",
      context_research_not_configured:
        "Веб-контекст не подключён. Текущий пакет пригоден с явными допущениями.",
      context_source_excluded: "Источник исключён. Активна новая версия пакета контекста.",
      context_version: "Версия пакета",
      context_confidence: "Уверенность",
      context_confidence_low: "Низкая",
      context_confidence_moderate: "Средняя",
      context_confidence_high: "Высокая",
      context_sources: "Источники",
      context_claims: "Утверждения",
      context_assumptions: "Допущения",
      context_gaps: "Открытые пробелы",
      context_scope: "Область",
      context_world: "Интерпретация мира",
      context_geography: "География",
      context_horizon: "Временной горизонт",
      context_agent_types: "Возможные типы агентов",
      context_resources: "Возможные ресурсы",
      context_actions: "Возможные действия",
      context_cutoff: "Историческая отсечка",
      context_no_cutoff: "Без отсечки",
      context_no_sources: "Активных источников пока нет.",
      context_no_claims: "Подтверждённых источниками утверждений пока нет.",
      context_no_gaps: "Существенных пробелов контекста нет.",
      context_source_pending: "Ожидает загрузки",
      context_source_active: "Активен",
      context_source_review: "Нужна проверка",
      context_exclude_source: "Исключить источник",
      context_exclude_source_named: "Исключить источник «%{source}»",
      context_published: "Опубликовано: %{date}",
      context_claim_source: "Источник · %{source}",
      context_add_web: "Добавить ограниченный веб-контекст",
      context_web_unavailable: "Веб-контекст не подключён",
      context_research_running: "Исследование выполняется",
      context_research_completed: "Исследование завершено",
      context_research_failed: "Исследование требует внимания",
      context_research_queued_status: "Исследование в очереди",
      context_research_plan: "План исследования",
      context_show_query: "Показать поисковый запрос",
      context_provider_calls: "Запросов к поиску: %{count}",
      context_grounding_user_data: "Данные пользователя",
      context_grounding_user_document: "Документ пользователя",
      context_grounding_external_source: "Внешний источник",
      context_grounding_analogue: "Аналог",
      context_grounding_model_prior: "Модельная предпосылка",
      context_grounding_assumption: "Допущение",
      context_gap_sourced_evidence: "Подтверждённые данные",
      context_gap_pending_sources: "Ожидающие источники",
      context_gap_failed_research_lane: "Неудачный поиск",
      context_gap_historical_cutoff: "Историческая отсечка",
      context_gap_source_excluded: "Исключённый источник",
      context_gap_source_retrieval_failed: "Недоступный источник",
      context_gap_research_not_run: "Исследование не выполнено",
      context_return_build: "Вернуться к сборке",
      population_title: "Модель популяции",
      population_lede:
        "Проверьте структурированные различия, которые создаст Hydra, — без склада синтетических биографий.",
      population_build_action: "Собрать популяцию",
      population_rebuild_action: "Пересобрать по текущему контексту",
      population_built: "Модель популяции активна.",
      population_ready: "Структура популяции готова",
      population_partial: "Популяция пригодна, но есть замечания импорта",
      population_version: "Версия модели",
      population_agents: "Моделируемые агенты",
      population_generated: "Создано",
      population_imported_count: "Импортировано",
      population_relationships: "Связи",
      population_seed: "Начальное число",
      population_compiler: "Компилятор",
      population_types: "Типы агентов",
      population_archetypes: "Архетипы",
      population_attributes: "Атрибуты",
      population_actions: "Доступные действия",
      population_resources: "Начальные ресурсы",
      population_grounding: "Ссылки на основания",
      population_agents_count: "%{count} агентов",
      population_remove_attribute: "Удалить",
      population_remove_attribute_named:
        "Удалить атрибут «%{attribute}» из типа «%{type}» и пересобрать",
      population_attribute_removed: "Атрибут удалён. Активна новая версия модели популяции.",
      population_last_attribute: "У каждого типа агента должен остаться хотя бы один атрибут.",
      population_sensitive: "Чувствительный · только агрегированно",
      population_sensitive_source:
        "Наблюдаемый и предоставленный признак; не выведен ради разнообразия.",
      population_sensitive_necessity: "Почему признак необходим",
      population_sensitive_lawful_basis: "Правовое основание",
      population_no_sensitive:
        "Защищённые и чувствительные признаки не выводились ради искусственного разнообразия.",
      population_topology: "Топология связей",
      population_representatives: "Представители",
      population_representatives_lede:
        "Читаемые карточки — необязательные проекции структурированного состояния. Для всей популяции текст не создаётся.",
      population_generate_persona: "Создать читаемую карточку",
      population_persona_projection: "Читаемая проекция · не исходное состояние",
      population_persona_pending: "Только структурированное состояние",
      population_structured_state: "Структурированное состояние",
      population_goals: "Цели",
      population_constraints: "Ограничения",
      population_current_state: "Текущее состояние",
      population_important_relationships: "Важные связи",
      population_grounding_count: "%{count} ссылок на основания",
      persona_generated: "Читаемая карточка представителя создана.",
      population_import: "Импорт структурированной популяции",
      population_import_lede:
        "Используйте CSV или JSON. Корректные строки сохраняются, ошибки показываются без значений полей.",
      population_import_kind: "Тип импорта",
      population_import_agents: "Агенты",
      population_import_relationships: "Связи между агентами",
      population_import_file: "Файл CSV или JSON",
      population_import_file_hint: "До 5 МБ · 10 000 строк агентов",
      population_id_column: "Столбец ID агента",
      population_type_column: "Столбец типа агента",
      population_archetype_column: "Столбец архетипа · необязательно",
      population_attribute_columns: "Столбцы атрибутов · необязательно",
      population_attribute_columns_hint: "Через запятую. Для переименования: источник:название.",
      population_resource_columns: "Столбцы ресурсов · необязательно",
      population_state_columns: "Столбцы состояния · необязательно",
      population_agent_mapping: "Сопоставление CSV агентов",
      population_relationship_mapping: "Сопоставление CSV связей",
      population_source_column: "Столбец исходного агента",
      population_target_column: "Столбец целевого агента",
      population_relationship_type_column: "Столбец типа связи",
      population_weight_column: "Столбец веса · необязательно",
      population_directed_column: "Столбец направления · необязательно",
      population_import_submit: "Проверить и импортировать",
      population_imported: "Корректные строки импортированы. Проверьте активную модель.",
      population_import_failed:
        "Ничего не импортировано. Проверьте файл и сопоставление столбцов.",
      population_import_result: "Последний импорт",
      population_import_valid: "Корректные строки",
      population_import_errors: "Строки с ошибками",
      population_import_no_errors: "Все импортированные строки прошли проверку.",
      population_import_row: "Строка %{row}",
      population_import_error_invalid_identifier:
        "Обязательный идентификатор отсутствует или некорректен.",
      population_import_error_invalid_object:
        "Сопоставленное значение не является структурированным объектом.",
      population_import_error_sensitive_attribute_requires_model_metadata:
        "Для чувствительного поля нужны явное обоснование необходимости и правовое основание в JSON-модели популяции.",
      population_import_error_duplicate_identifier: "Идентификатор повторяется.",
      population_import_error_invalid_weight: "Вес связи должен быть от 0 до 1.",
      population_import_error_invalid_boolean: "Направление должно быть true или false.",
      population_import_error_self_relationship: "Связь не может вести к тому же агенту.",
      population_import_error_default: "Строка не соответствует выбранному сопоставлению.",
      population_return_build: "Вернуться к сборке"
    }
  }

  def t(locale, key) do
    locale = if locale in ["en", "ru"], do: locale, else: "en"
    get_in(@copy, [locale, key]) || get_in(@copy, ["en", key]) || to_string(key)
  end

  def interpolate(locale, key, values) do
    Enum.reduce(values, t(locale, key), fn {name, value}, copy ->
      String.replace(copy, "%{#{name}}", to_string(value))
    end)
  end
end
